### PR TITLE
CyberPython

### PR DESCRIPTION
**Pull request by cybersecuritylearning**
A hands on platform which makes you to do your own research in order to learn and improve your skills

### CODE REVIEW

**Comment by sujayadkesar** [comment]
Hi @cybersecuritylearning  i have reviewed your commit but the link attached to cyberpython is leading to http://pythoncyber.go.ro:4443/ which is not secure and port number is also suspicious so i am closing this pull request

let me know if you have any other changes! 

Thanks!

**Comment by cybersecuritylearning** [comment]
Hello, no it is legitimate, it's under construction, when it will be ready
I will make a PR again if its ok

**Comment by sujayadkesar** [comment]
Sure feel free to add few more or the changes as needed!

**Comment by sujayadkesar** [comment]
Sure feel free to add few more  or changes as needed!

**Pull request closed without merging**
